[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#FFAAAA'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#DE7C7D'

# Color used for almost all text
textColor = '#F6EFBD'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
